In [1]:
import numpy as np
import anndata
import pandas as pd
import scanpy as sc
import scipy

In [ ]:
import ott

In [ ]:
import moscot

In [ ]:
import jax

In [ ]:
jax.devices()

In [ ]:
from jax.lib import xla_bridge

In [ ]:
print(xla_bridge.get_backend().platform)

In [3]:
import jax

In [4]:
jax.devices()

[CpuDevice(id=0)]

In [6]:
from jax.lib import xla_bridge

In [7]:
print(xla_bridge.get_backend().platform)

cpu


In [1]:
import ott

/home/mgander/miniconda3/envs/mc/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/home/mgander/miniconda3/envs/mc/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/home/mgander/miniconda3/envs/mc/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)


In [2]:
ott

<module 'ott' from '/home/mgander/miniconda3/envs/mc/lib/python3.10/site-packages/ott/__init__.py'>

In [1]:
import moscot

ModuleNotFoundError: No module named 'moscot'

In [3]:
import jax

In [1]:
import moscot

/home/mgander/miniconda3/envs/phos/lib/python3.10/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
2023-04-21 09:21:27.467317: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR


XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

In [1]:
from jax.lib import xla_bridge

In [2]:
print(xla_bridge.get_backend().platform)

gpu


In [1]:
pip uninstall moscot

Found existing installation: moscot 0.1.0
Uninstalling moscot-0.1.0:
  Would remove:
    /home/mgander/miniconda3/envs/phos/lib/python3.10/site-packages/moscot-0.1.0.dist-info/*
    /home/mgander/miniconda3/envs/phos/lib/python3.10/site-packages/moscot/*
Proceed (Y/n)? Note: you may need to restart the kernel to use updated packages.


In [2]:
import moscot

/home/mgander/miniconda3/envs/phos/lib/python3.10/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
2023-04-18 16:32:16.793700: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.


XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

In [2]:
import cudnn

ModuleNotFoundError: No module named 'cudnn'

In [ ]:
Loaded runtime CuDNN library: 8.1.1 but source was compiled with: 8.6.0. 
CuDNN library needs to have matching major version and equal or higher minor version. 
If using a binary install, upgrade your CuDNN library.

In [3]:
from moscot.problems.time._lineage import TemporalProblem
from moscot.backends.ott._solver import SinkhornSolver

2023-04-18 16:04:07.841980: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.1.1 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-04-18 16:04:07.851528: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:54] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:641) dnn != nullptr 
*** Begin stack trace ***
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	_PyObject_MakeTpCall
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEva

XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:641) dnn != nullptr 

In [4]:
# Setting jax to use float64, makes the algorithm more stable
from jax.config import config
config.update("jax_enable_x64", True)

import sys
sys.path.append('/home/icb/manuel.gander/github_repos/moscot-main/src/moscot')
sys.path.append('/home/icb/manuel.gander/github_repos/moscot')
#sys.path.append('/home/icb/manuel.gander/github_repos/moscot-master')

In [ ]:
import moscot
from moscot.problems.time._lineage import TemporalProblem
from moscot.backends.ott._solver import SinkhornSolver

/home/icb/manuel.gander/miniconda3/envs/m/lib/python3.10/site-packages/docrep/decorators.py:43: SyntaxWarning: 'dataset.parameters' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)


In [6]:
from moscot.problems.time._lineage import TemporalProblem

ModuleNotFoundError: No module named 'moscot'

In [5]:
moscot

NameError: name 'moscot' is not defined

In [3]:
TemporalProblem

moscot.problems.time._lineage.TemporalProblem

In [4]:
import moscot

In [5]:
moscot

<module 'moscot' from '/home/icb/manuel.gander/miniconda3/lib/python3.9/site-packages/moscot/__init__.py'>

In [112]:
from importlib import reload

import sys
sys.path.append('/home/icb/manuel.gander/moscotTime_Reproducibility/Notebooks/Python_notebooks')
import Utils

Utils=reload(Utils)

In [88]:
Path="/home/icb/manuel.gander/moscotTime_Reproducibility/Data"
ts=['E3.5', 'E4.5', 'E5.25', 'E5.5', 'E6.25', 'E6.5', 'E6.75', 'E7.0', 'E7.25', 'E7.5', 'E7.75', 'E8.0', 'E8.25', 'E8.5a', 'E8.5b', 'E9.5', 'E10.5', 'E11.5', 'E12.5', 'E13.5']

In [89]:
i=2
ts0=ts[0]
ts1=ts[1]

In [113]:
i=2
ts0=ts[0]
ts1=ts[1]

adata=Utils.load_adata(ts0, ts1)
# Raw count matrix not needed here, but causes problems in "score_genes_for_marginals"
del adata.raw

In [115]:
tp=TemporalProblem(adata)
tp.score_genes_for_marginals(gene_set_proliferation='mouse',  gene_set_apoptosis='mouse')
tp = tp.prepare('day', joint_attr=f'X_pcaS')

In [117]:
batch_size=10**6

In [118]:
eps=0.05
tau1=0.99
tau2=0.9999

In [121]:
result=tp.solve(batch_size=batch_size, epsilon=eps, tau_a=tau1, tau_b=tau2, scale_cost="mean", max_iterations=10**6)

INFO     Solving problem BirthDeathProblem[stage='solved', shape=(90, 67)].                                        


In [124]:
dir(result[(3.5, 4.5)])

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_a',
 '_abc_impl',
 '_adata_src',
 '_adata_tgt',
 '_apoptosis_key',
 '_b',
 '_create_marginals',
 '_estimate_marginals',
 '_get_mass',
 '_handle_linear',
 '_local_pca_callback',
 '_metadata',
 '_prior_growth',
 '_problem_kind',
 '_proliferation_key',
 '_scaling',
 '_solution',
 '_solver',
 '_src_key',
 '_src_obs_mask',
 '_src_var_mask',
 '_stage',
 '_tgt_key',
 '_tgt_obs_mask',
 '_tgt_var_mask',
 '_x',
 '_xy',
 '_y',
 'a',
 'adata',
 'adata_src',
 'adata_tgt',
 'apoptosis_key',
 'b',
 'delta',
 'posterior_growth_rates',
 'prepare',
 'prior_growth_rates',
 'problem_kind',
 'proliferat

In [125]:
result[(3.5, 4.5)].prior_growth_rates

array([1.74635174, 2.58819747, 2.28579773, 1.10982672, 1.77890424,
       1.36235977, 2.01571155, 1.64890756, 1.45195649, 1.66700088,
       1.03753039, 1.5426195 , 1.65465152, 1.35361   , 1.43312474,
       1.03071585, 1.84696893, 1.47390778, 1.79060743, 1.3101418 ,
       1.78467567, 1.60605323, 1.28677735, 1.21873822, 1.22032073,
       1.5157602 , 1.61381278, 1.26514752, 1.75844924, 1.83664127,
       1.5410088 , 1.44346247, 1.35858502, 1.21669276, 1.77446452,
       1.54702357, 1.45859248, 1.62241706, 1.56301952, 0.8905782 ,
       1.30606454, 1.16530294, 1.74136154, 1.27472795, 1.47030881,
       1.36049107, 1.50054964, 1.16731084, 1.71458029, 0.89891862,
       1.27368849, 1.36723378, 1.44226697, 1.2712985 , 1.1730001 ,
       1.78454436, 1.90461412, 1.32664719, 1.31688386, 0.83342317,
       1.26541533, 1.90625208, 1.61279114, 1.05491114, 1.45819064,
       1.81738972, 1.00426039, 1.06404513, 1.39366979, 1.93536837,
       1.64538766, 1.22999253, 2.34962313, 1.80549249, 0.96383

In [126]:
result[(3.5, 4.5)].posterior_growth_rates

array([1.5163205 , 2.262108  , 2.2294397 , 0.6914981 , 1.2385108 ,
       1.4204378 , 1.6313179 , 1.2801179 , 1.0793808 , 1.1423699 ,
       0.9716743 , 1.4996556 , 1.2865893 , 1.4681895 , 1.429772  ,
       1.1128207 , 1.969939  , 1.5912064 , 1.9534299 , 1.4232541 ,
       1.6828415 , 1.600497  , 1.2506745 , 0.86941737, 1.3322581 ,
       1.6551887 , 1.7712574 , 1.387959  , 1.4331528 , 1.9446251 ,
       1.6640416 , 1.5643946 , 1.468681  , 1.3328097 , 1.4271245 ,
       1.6333416 , 1.5847436 , 1.7624037 , 1.7033474 , 0.9729271 ,
       1.4094694 , 1.2636817 , 1.8989061 , 1.308983  , 1.5923434 ,
       1.3189608 , 1.5710067 , 1.2725681 , 1.8614746 , 0.87953657,
       1.0369346 , 1.4957498 , 1.540974  , 1.3872588 , 1.1487161 ,
       1.9339346 , 2.047877  , 1.4443278 , 1.3694973 , 0.91033727,
       1.3745    , 2.0698373 , 1.7068238 , 1.1375479 , 1.4317881 ,
       1.6790253 , 1.0609534 , 1.1524457 , 1.467218  , 2.089247  ,
       1.77824   , 1.3371664 , 2.5694544 , 1.9794387 , 1.00488

In [ ]:
save(dir_path[, file_prefix, overwrite])

In [140]:
tp.save(f'{Path}/moscot_maps/', f'{ts0}')

INFO     Successfully saved the problem as                                                                         
         `/home/icb/manuel.gander/moscotTime_Reproducibility/Data/moscot_maps/E3.5_TemporalProblem.pkl`            


In [144]:
tp=tp.load(f'{Path}/moscot_maps/{ts0}_TemporalProblem.pkl')

In [148]:
tp[(3.5, 4.5)].prior_growth_rates

array([1.74635174, 2.58819747, 2.28579773, 1.10982672, 1.77890424,
       1.36235977, 2.01571155, 1.64890756, 1.45195649, 1.66700088,
       1.03753039, 1.5426195 , 1.65465152, 1.35361   , 1.43312474,
       1.03071585, 1.84696893, 1.47390778, 1.79060743, 1.3101418 ,
       1.78467567, 1.60605323, 1.28677735, 1.21873822, 1.22032073,
       1.5157602 , 1.61381278, 1.26514752, 1.75844924, 1.83664127,
       1.5410088 , 1.44346247, 1.35858502, 1.21669276, 1.77446452,
       1.54702357, 1.45859248, 1.62241706, 1.56301952, 0.8905782 ,
       1.30606454, 1.16530294, 1.74136154, 1.27472795, 1.47030881,
       1.36049107, 1.50054964, 1.16731084, 1.71458029, 0.89891862,
       1.27368849, 1.36723378, 1.44226697, 1.2712985 , 1.1730001 ,
       1.78454436, 1.90461412, 1.32664719, 1.31688386, 0.83342317,
       1.26541533, 1.90625208, 1.61279114, 1.05491114, 1.45819064,
       1.81738972, 1.00426039, 1.06404513, 1.39366979, 1.93536837,
       1.64538766, 1.22999253, 2.34962313, 1.80549249, 0.96383