In [2]:
import numpy as np
import anndata
import pandas as pd
import scanpy as sc
import scipy

In [3]:
import moscot

In [6]:
from moscot.problems.time._lineage import TemporalProblem

In [ ]:
    "# The lines below are useful to customize RAM-Memory usage\n",
    "import os\n",
    "# By default, OTT takes 90% of RAM-memory. Using the line below it uses exactly how much it needs\n",
    "os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'\n",
    "# This frees RAM-Memory if no longer needed, but might slow down computations (I didn't observe that)\n",
    "os.environ['XLA_PYTHON_CLIENT_ALLOCATOR']='platform'\n",

In [ ]:
import numpy as np
import anndata
import pandas as pd
import scanpy as sc
import scipy
from moscot.problems.time._lineage import TemporalProblem

Path="/home/mgander/Unrelated/moscotTime_Reproducibility/Data"
ts=['E3.5', 'E4.5', 'E5.25', 'E5.5', 'E6.25', 'E6.5', 'E6.75', 'E7.0', 'E7.25', 'E7.5', 'E7.75', 'E8.0', 'E8.25', 'E8.5a', 'E8.5b', 'E9.5', 'E10.5', 'E11.5', 'E12.5', 'E13.5']


i=2
ts0=ts[0]
ts1=ts[1]

adata=sc.read(f"{Path}/anndatas/Comb_anndatas/adata_{ts0}_{ts1}.h5ad")
# Raw count matrix not needed here, but causes problems in "score_genes_for_marginals"
del adata.raw

tp=TemporalProblem(adata)
tp.score_genes_for_marginals(gene_set_proliferation='mouse',  gene_set_apoptosis='mouse')
tp = tp.prepare('day', joint_attr=f'X_pcaS')

batch_size=10**6
eps=0.05
tau1=0.99
tau2=0.99+0.01*tau1

result=tp.solve(batch_size=batch_size, epsilon=eps, tau_a=tau1, tau_b=tau2, scale_cost="mean", max_iterations=10**6)

tp.save(f'{Path}/moscot_maps/', f'{ts0}')

In [8]:
# Setting jax to use float64, makes the algorithm more stable
#from jax.config import config
#config.update("jax_enable_x64", True)

#import sys
#sys.path.append('/home/icb/manuel.gander/github_repos/moscot-main/src/moscot')
#sys.path.append('/home/icb/manuel.gander/github_repos/moscot')
#sys.path.append('/home/icb/manuel.gander/github_repos/moscot-master')

In [16]:
Path="/home/mgander/Unrelated/moscotTime_Reproducibility/Data"
ts=['E3.5', 'E4.5', 'E5.25', 'E5.5', 'E6.25', 'E6.5', 'E6.75', 'E7.0', 'E7.25', 'E7.5', 'E7.75', 'E8.0', 'E8.25', 'E8.5a', 'E8.5b', 'E9.5', 'E10.5', 'E11.5', 'E12.5', 'E13.5']

from importlib import reload

import sys
sys.path.append('/home/mgander/Unrelated/moscotTime_Reproducibility/Notebooks/Python_notebooks')
import Utils

Utils=reload(Utils)

In [18]:
i=2
ts0=ts[0]
ts1=ts[1]

adata=sc.read(f"{Path}/anndatas/Comb_anndatas/adata_{ts0}_{ts1}.h5ad")
# Raw count matrix not needed here, but causes problems in "score_genes_for_marginals"
del adata.raw

In [19]:
tp=TemporalProblem(adata)
tp.score_genes_for_marginals(gene_set_proliferation='mouse',  gene_set_apoptosis='mouse')
tp = tp.prepare('day', joint_attr=f'X_pcaS')

In [20]:
batch_size=10**6

In [21]:
batch_size=10**6
eps=0.05
tau1=0.99
tau2=0.9999

In [22]:
result=tp.solve(batch_size=batch_size, epsilon=eps, tau_a=tau1, tau_b=tau2, scale_cost="mean", max_iterations=10**6)

INFO     Solving problem BirthDeathProblem[stage='prepared', shape=(90, 67)].                                      


In [23]:
tp.save(f'{Path}/moscot_maps/', f'{ts0}')

INFO     Successfully saved the problem as                                                                         
         `/home/mgander/Unrelated/moscotTime_Reproducibility/Data/moscot_maps/E3.5_TemporalProblem.pkl`            


In [125]:
result[(3.5, 4.5)].prior_growth_rates

array([1.74635174, 2.58819747, 2.28579773, 1.10982672, 1.77890424,
       1.36235977, 2.01571155, 1.64890756, 1.45195649, 1.66700088,
       1.03753039, 1.5426195 , 1.65465152, 1.35361   , 1.43312474,
       1.03071585, 1.84696893, 1.47390778, 1.79060743, 1.3101418 ,
       1.78467567, 1.60605323, 1.28677735, 1.21873822, 1.22032073,
       1.5157602 , 1.61381278, 1.26514752, 1.75844924, 1.83664127,
       1.5410088 , 1.44346247, 1.35858502, 1.21669276, 1.77446452,
       1.54702357, 1.45859248, 1.62241706, 1.56301952, 0.8905782 ,
       1.30606454, 1.16530294, 1.74136154, 1.27472795, 1.47030881,
       1.36049107, 1.50054964, 1.16731084, 1.71458029, 0.89891862,
       1.27368849, 1.36723378, 1.44226697, 1.2712985 , 1.1730001 ,
       1.78454436, 1.90461412, 1.32664719, 1.31688386, 0.83342317,
       1.26541533, 1.90625208, 1.61279114, 1.05491114, 1.45819064,
       1.81738972, 1.00426039, 1.06404513, 1.39366979, 1.93536837,
       1.64538766, 1.22999253, 2.34962313, 1.80549249, 0.96383

In [126]:
result[(3.5, 4.5)].posterior_growth_rates

array([1.5163205 , 2.262108  , 2.2294397 , 0.6914981 , 1.2385108 ,
       1.4204378 , 1.6313179 , 1.2801179 , 1.0793808 , 1.1423699 ,
       0.9716743 , 1.4996556 , 1.2865893 , 1.4681895 , 1.429772  ,
       1.1128207 , 1.969939  , 1.5912064 , 1.9534299 , 1.4232541 ,
       1.6828415 , 1.600497  , 1.2506745 , 0.86941737, 1.3322581 ,
       1.6551887 , 1.7712574 , 1.387959  , 1.4331528 , 1.9446251 ,
       1.6640416 , 1.5643946 , 1.468681  , 1.3328097 , 1.4271245 ,
       1.6333416 , 1.5847436 , 1.7624037 , 1.7033474 , 0.9729271 ,
       1.4094694 , 1.2636817 , 1.8989061 , 1.308983  , 1.5923434 ,
       1.3189608 , 1.5710067 , 1.2725681 , 1.8614746 , 0.87953657,
       1.0369346 , 1.4957498 , 1.540974  , 1.3872588 , 1.1487161 ,
       1.9339346 , 2.047877  , 1.4443278 , 1.3694973 , 0.91033727,
       1.3745    , 2.0698373 , 1.7068238 , 1.1375479 , 1.4317881 ,
       1.6790253 , 1.0609534 , 1.1524457 , 1.467218  , 2.089247  ,
       1.77824   , 1.3371664 , 2.5694544 , 1.9794387 , 1.00488

In [ ]:
save(dir_path[, file_prefix, overwrite])

In [140]:
tp.save(f'{Path}/moscot_maps/', f'{ts0}')

INFO     Successfully saved the problem as                                                                         
         `/home/icb/manuel.gander/moscotTime_Reproducibility/Data/moscot_maps/E3.5_TemporalProblem.pkl`            


In [144]:
tp=tp.load(f'{Path}/moscot_maps/{ts0}_TemporalProblem.pkl')

In [148]:
tp[(3.5, 4.5)].prior_growth_rates

array([1.74635174, 2.58819747, 2.28579773, 1.10982672, 1.77890424,
       1.36235977, 2.01571155, 1.64890756, 1.45195649, 1.66700088,
       1.03753039, 1.5426195 , 1.65465152, 1.35361   , 1.43312474,
       1.03071585, 1.84696893, 1.47390778, 1.79060743, 1.3101418 ,
       1.78467567, 1.60605323, 1.28677735, 1.21873822, 1.22032073,
       1.5157602 , 1.61381278, 1.26514752, 1.75844924, 1.83664127,
       1.5410088 , 1.44346247, 1.35858502, 1.21669276, 1.77446452,
       1.54702357, 1.45859248, 1.62241706, 1.56301952, 0.8905782 ,
       1.30606454, 1.16530294, 1.74136154, 1.27472795, 1.47030881,
       1.36049107, 1.50054964, 1.16731084, 1.71458029, 0.89891862,
       1.27368849, 1.36723378, 1.44226697, 1.2712985 , 1.1730001 ,
       1.78454436, 1.90461412, 1.32664719, 1.31688386, 0.83342317,
       1.26541533, 1.90625208, 1.61279114, 1.05491114, 1.45819064,
       1.81738972, 1.00426039, 1.06404513, 1.39366979, 1.93536837,
       1.64538766, 1.22999253, 2.34962313, 1.80549249, 0.96383